gruntjs/grunt

Gruntfile.js
package.json

I'm currently working on setting up a Jenkins job that tests grunt against Node.js' v0.12 branch (which contains the code for the upcoming 0.12 stable version). While doing so, I wanted to be able to run all tests (the equivalent of `npm test`) and parse the results so that I could examine tests failures easily.
Currently, the tests results are outputted to standard error or output using the default reporter, and it makes parsing tests results difficult.
Having a separate npm script like `test-ci` that outputs tests results to files with a standard format that is easy to parse by a program (TAP) is very helpful.
This change also adds `grunt-cli` as a local dependency, so that we don't have to manage this dependency at the system level where the continuous integration tools are installed. …

Add test-ci npm script that outputs tests results in a separate file.

---

lib/grunt/fail.js

The presence of the word errors causes automated build result processing to present a false positive for failure.  It is commonplace for automation frameworks to look for the presence of the word "error" or "errors." Simply parsing the message in the log output often causes alarm within our organization.
Please consider this change.

Remove the words 'without errors.' after successfully running tasks

---

lib/grunt.js
package.json

There is quite old version 1.3.3 which already has some issues with scripts written in 1.9.2. Unfortunately it has issues other way around too. There are some changes in latest version that can break old code. 
In my opinion the Grunt should not have a coffee-script as a direct dependency. It should just use the version that is installed for a project. Maybe change this to Grunt 0.5 or whatever is next?

Update coffee script

---

lib/grunt/template.js

This resolves "_ is not defined" errors when using templates.
See also: https://github.com/lodash/lodash/issues/484

extend _.templateSettings instead of overriding it

---

lib/grunt/file.js
test/grunt/file_test.js

I suspect this will make the options parameter work as originally intended.

Pass the grunt.file.write options on to writeFileSync

---

appveyor.yml

this disables appveyor cache otherwise npm will get stuck installing

disable appveyor cache

---

test/grunt/file_test.js

Ref #1442
Windows requires Administrator privileges to create symlinks, give a warning to
that effect but allow tests to complete (and fail).
I thought about putting all the link-related tests into a single unit test but hey, it's gonna fail no matter what and the names of the tests make it pretty clear what happened.

Tests: Warn if symlinks can't be created, but continue tests

---

lib/util/task.js
test/util/task_test.js

* calling the callback multiple times would skip queued task

Prevent async callback from being called multiple times

---

lib/grunt/file.js

Since iconv.decode() handles removing or preserving the BOM (according to the option given), the additional code to strip any BOM that might exist is unnecessary.
Removing this duplicate code for cleanliness/DRYness.

Removing duplicate BOM strip code

---

package.json

This is a fix as just installing `grunt-cli` as a dependency doesn't actually create the appropriate binary as reported by @vladikoff.
@vladikoff could you please review? Thanks!
```shell
npm i gruntjs/grunt#fix-cli-bin
./node_modules/.bin/grunt
```

Ensure a grunt bin gets created upon install

---

lib/grunt/cli.js
package.json

Ref gruntjs/grunt-cli#102
Uses the newly created https://github.com/gruntjs/grunt-known-options to share the known Grunt options between grunt and grunt-cli.

Use grunt-known-options for shared options between Grunt and grunt-cli

---

bin/grunt
package.json

Fixes GH-1499
This fixes the issue where `grunt-cli` might not yet exist when npm is trying to create a binary.
@vladikoff Mind giving this a full vetting? I tested on `npm@2` and `npm@3` but want to make sure I'm not missing something big with this. Thanks!

Use local bin that points to grunt-cli

---

package.json

I have noticed that package.json for gruntjs doesn't provide correct git repository url and that is why I have fixed it providing https://github.com/gruntjs/grunt.git instead of gruntjs/grunt.
I have validated it by [package.json validator](http://package-json-validator.com/) and the screenshot is attached.

Provide correct git repository URL in package.json

---

README.md

Followup to @kborchers's email on JSF adopting FOSSA for license scanning.
Congrats Grunt team on the passing license scan!  Here's a green badge and report.

Add license report and scan badge

---

.travis.yml

Add support for Node.js v7 and v8.
Updated .travis.yml.

Add Node.js v7 and v8 to Travis CI

---

lib/grunt/file.js
package.json

Fixes GH-1511
Fixes GH-1351
This uses the well vetted [mkdirp](https://www.npmjs.com/package/mkdirp) module within `file.mkdir` which fixes some bugs people are running into in the above two issues.

Use mkdirp for file.mkdir

---

lib/grunt/template.js

Whilst working on the Reproducible Builds effort [0], we noticed
that grunt can generate non-reproducible output. This is affecting the
reproducibility status other packages (such as jquery-tablesorter) that
set a "pkg.banner" such as:
<%= grunt.template.today("mm-dd-yyyy")
[0] https://reproducible-builds.org/
Signed-off-by: Chris Lamb <chris@chris-lamb.co.uk>

Use SOURCE_DATE_EPOCH to render dates in template.

---

lib/grunt/task.js
test/fixtures/load-npm-tasks/test-package/package.json
test/gruntfile/load-npm-tasks.js

allow usage of grunt plugins that are located in any location that
is visible to Node.js and NPM, instead of `node_modules` directly
inside package that have a dev dependency to these plugins.
Fix #1676.

support monorepos

---

lib/grunt.js
package.json

https://github.com/gruntjs/grunt-cli/pull/117 removes the need for coffeescript in grunt by using Liftoff instead.
To ease transition, if `coffeescript` is still around, Grunt will attempt to load it. If it is not, and the user loads a CoffeeScript file, Grunt will print a useful error indicating that the `coffeescript` package should be installed as a dev dependency.
This is considerably more user-friendly than dropping the `require` entirely, but doing so is feasible with the latest `grunt-cli` as users may simply use `grunt --require coffeescript/register`.

Remove coffeescript from dependencies.

---

lib/grunt/file.js
test/grunt/file_test.js

Ran into an issue where some symlinks weren't being reported as such when tested via `grunt.file.isLink`. 
Turns out relative symlinks show up as nonexistent to Node's `fs.exists`, but they are actually recognized correctly via `fs.lstatSync`.
I've removed the `file.exists` check in `grunt.file.isLink` so that relative links work, and then am handling nonexistent files within the `catch`.
Added tests, and confirmed that they all pass on OS X Yosemite, Ubuntu 14.04, and Windows 7, and were failing [before the fixes were made](https://github.com/greglittlefield-wf/grunt/compare/recognize-relative-links-failing).

Fix issue where grunt.file.isLink() returned false for relative links

---

lib/grunt/help.js

If very long command names are registered, grunt --help runs
out of memory trying to generate the help table. This commit
adjusts the width to be at least 20 longer than the maximal
command length.
Fixes #1696

Avoiding infinite loop on very long command names.

---

lib/grunt/option.js
test/grunt/option_test.js

Expose grunt option keys for use with grunt tasks
Example use case : saving all current options to json, for developer preferences
grunt.registerTask('gen', 'Generate based on last settings', function () {
// TODO
});

FEATURE - Expose Grunt Option Keys for Ease of Use

---

lib/grunt/file.js
package.json

Remove path-is-absolute dependency

Remove path-is-absolute dependency

---

lib/grunt/file.js
test/grunt/file_test.js

For previous behaviour please use the following:
```
readYAML('test/fixtures/utf8.yaml', null, {unsafeLoad: true});
```
@shama got a sec for an r? 👀

Switch to use `safeLoad` for loading YML files via `file.readYAML`.

---

.github/workflows/test.yml

This PR bumps GitHub workflow actions to their latest versions, thus avoiding deprecation warnings.

Bump GitHub workflow actions to latest versions

---

package.json

* grunt-cli updated to nopt 4.x in https://github.com/gruntjs/grunt-cli/pull/117
* grunt-cli updated to nopt 5.0 in https://github.com/gruntjs/grunt-cli/pull/156
* changelog: https://github.com/npm/nopt/blob/v5.0.0/CHANGELOG.md
The simple usage of `nopt(known, alias, argv, 2)` has remained unchanged through both changes, same as in this repo.
Installation of latest grunt- produces a warning:
> npm WARN deprecated osenv@0.1.5: This package is no longer supported.
This package was used by nopt to call `os.homedir()` which has been built-in since Node.js 2. The dependency was removed in nopt 5.0.0 with https://github.com/npm/nopt/commit/5c0e45b2f94414c074270b133e90c77ec35f5a4b.
Newer versions of nopt are available, but those raise the required Node.js engine level. In order to make this safe …

Update from nopt 3.x to nopt 5.0.0

---

.github/workflows/test.yml

Adds Node.js 22 to version matrix of CI workflow. Also updates actions used in pipeline from V3 to V4. The V3 version was giving deprecation warnings when run.

CI: add Node.js 22
